=== Abrahamrc94/DAW/LMSGI/Trabajos/Eclipse/EjerciciosXSD1/Ej4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">
	<xsi:element name = "biblioteca">
		<xsi:complexType>
			<xsi:sequence>
				<xsi:element name = "libro" maxOccurs = "unbounded" minOccurs = "0">
					<xsi:complexType>
						<xsi:sequence>
							<xsi:element name = "autor"/>
							<xsi:element name = "titulo"/>
							<xsi:element name = "codigo">
								<xsi:simpleType>
									<xsi:restriction base = "xsi:integer">
										<xsi:minInclusive value="1"/>
										<xsi:maxInclusive value="9999"/>
									</xsi:restriction>
								</xsi:simpleType>
							</xsi:element>
						</xsi:sequence>
					</xsi:complexType>
				</xsi:element>
			</xsi:sequence>
		</xsi:complexType>
	</xsi:element>
</xsi:schema>

=== Abrahamrc94/DAW/LMSGI/Trabajos/Eclipse/EjerciciosXSD1/Ej4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="Ej4.xsd">
	<libro>
		<autor>Miguel de Cervantes Saavedra</autor>
		<titulo>El Quijote de la Mancha</titulo>
		<codigo>123</codigo>
    </libro>
 	<libro>
  		<autor>Pablo Neruda</autor>
  		<titulo>Veinte poemas de amor y una canciÃ³n desesperada</titulo>
  		<codigo>124</codigo>
 	</libro>
</biblioteca>
